owner: nueip
repo: upptime

sites:
  - name: NUEiP Official website
    icon: https://www.nueip.com/favicon.ico
    url: https://www.nueip.com
  - name: NUEiP HRM
    icon: https://cloud.nueip.com/assets/img/logo/hrm_logo_service.svg
    url: https://cloud.nueip.com
  - name: NUEiP CRM
    icon: https://cloud.nueip.com/assets/img/logo/crm_logo_service.svg
    url: https://crm.nueip.com
  - name: NUEiP Bi
    icon: https://cloud.nueip.com/assets/img/logo/bi_logo_service.svg
    url: https://bi.nueip.com

status-website:
  name: Status Dashboard
  cname: status.nueip.com
  logoUrl: https://www.nueip.com/img/logo.svg
  favicon: https://cloud.nueip.com/favicon.ico
  faviconSvg: https://cloud.nueip.com/favicon.ico
  robotsText: "User-agent: * \n Disallow: /"
  navbar:
    - title: State
      href: /
    - title: About
      href: https://www.nueip.com/aboutus
    - title: Contact
      href: https://www.nueip.com/contactus

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
